/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1beta1
 * Contact: eng@timeplus.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AddSinkRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-27T00:55:54.866Z")
public class AddSinkRequest {
  @SerializedName("sink_id")
  private String sinkId = null;

  public AddSinkRequest sinkId(String sinkId) {
    this.sinkId = sinkId;
    return this;
  }

   /**
   * Get sinkId
   * @return sinkId
  **/
  @ApiModelProperty(value = "")
  public String getSinkId() {
    return sinkId;
  }

  public void setSinkId(String sinkId) {
    this.sinkId = sinkId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddSinkRequest addSinkRequest = (AddSinkRequest) o;
    return Objects.equals(this.sinkId, addSinkRequest.sinkId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sinkId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddSinkRequest {\n");
    
    sb.append("    sinkId: ").append(toIndentedString(sinkId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

