/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1beta1
 * Contact: eng@timeplus.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * APIKey
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-27T00:55:54.866Z")
public class APIKey {
  @SerializedName("created_at")
  private Integer createdAt = null;

  @SerializedName("expire_at")
  private Integer expireAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("permissions")
  private List<String> permissions = null;

  public APIKey createdAt(Integer createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * creation time represented as the number of seconds elapsed since January 1, 1970 UTC
   * @return createdAt
  **/
  @ApiModelProperty(example = "1257894000", value = "creation time represented as the number of seconds elapsed since January 1, 1970 UTC")
  public Integer getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  public APIKey expireAt(Integer expireAt) {
    this.expireAt = expireAt;
    return this;
  }

   /**
   * expiration time represented as the number of seconds elapsed since January 1, 1970 UTC
   * @return expireAt
  **/
  @ApiModelProperty(example = "1257894000", value = "expiration time represented as the number of seconds elapsed since January 1, 1970 UTC")
  public Integer getExpireAt() {
    return expireAt;
  }

  public void setExpireAt(Integer expireAt) {
    this.expireAt = expireAt;
  }

  public APIKey id(String id) {
    this.id = id;
    return this;
  }

   /**
   * a string that identifies an API key, readonly.
   * @return id
  **/
  @ApiModelProperty(value = "a string that identifies an API key, readonly.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public APIKey name(String name) {
    this.name = name;
    return this;
  }

   /**
   * the name of the API key
   * @return name
  **/
  @ApiModelProperty(value = "the name of the API key")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public APIKey permissions(List<String> permissions) {
    this.permissions = permissions;
    return this;
  }

  public APIKey addPermissionsItem(String permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<String>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * list of permissions associated with the API key
   * @return permissions
  **/
  @ApiModelProperty(example = "[\"read:query\",\"write:query\"]", value = "list of permissions associated with the API key")
  public List<String> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<String> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIKey apIKey = (APIKey) o;
    return Objects.equals(this.createdAt, apIKey.createdAt) &&
        Objects.equals(this.expireAt, apIKey.expireAt) &&
        Objects.equals(this.id, apIKey.id) &&
        Objects.equals(this.name, apIKey.name) &&
        Objects.equals(this.permissions, apIKey.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, expireAt, id, name, permissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIKey {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expireAt: ").append(toIndentedString(expireAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

