/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BatchingPolicy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-06T23:45:14.171Z")
public class BatchingPolicy {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("time_ms")
  private Integer timeMs = null;

  public BatchingPolicy count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * The max result count per batch
   * @return count
  **/
  @ApiModelProperty(value = "The max result count per batch")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public BatchingPolicy timeMs(Integer timeMs) {
    this.timeMs = timeMs;
    return this;
  }

   /**
   * The max interval per batch in milliseconds
   * @return timeMs
  **/
  @ApiModelProperty(value = "The max interval per batch in milliseconds")
  public Integer getTimeMs() {
    return timeMs;
  }

  public void setTimeMs(Integer timeMs) {
    this.timeMs = timeMs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchingPolicy batchingPolicy = (BatchingPolicy) o;
    return Objects.equals(this.count, batchingPolicy.count) &&
        Objects.equals(this.timeMs, batchingPolicy.timeMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, timeMs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchingPolicy {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    timeMs: ").append(toIndentedString(timeMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

