/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1beta1
 * Contact: eng@timeplus.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.StreamDef;
import java.io.IOException;

/**
 * ConnectionConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-27T00:55:54.866Z")
public class ConnectionConfig {
  @SerializedName("auto_create")
  private Boolean autoCreate = null;

  @SerializedName("stream_definition")
  private StreamDef streamDefinition = null;

  public ConnectionConfig autoCreate(Boolean autoCreate) {
    this.autoCreate = autoCreate;
    return this;
  }

   /**
   * Get autoCreate
   * @return autoCreate
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutoCreate() {
    return autoCreate;
  }

  public void setAutoCreate(Boolean autoCreate) {
    this.autoCreate = autoCreate;
  }

  public ConnectionConfig streamDefinition(StreamDef streamDefinition) {
    this.streamDefinition = streamDefinition;
    return this;
  }

   /**
   * Get streamDefinition
   * @return streamDefinition
  **/
  @ApiModelProperty(value = "")
  public StreamDef getStreamDefinition() {
    return streamDefinition;
  }

  public void setStreamDefinition(StreamDef streamDefinition) {
    this.streamDefinition = streamDefinition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionConfig connectionConfig = (ConnectionConfig) o;
    return Objects.equals(this.autoCreate, connectionConfig.autoCreate) &&
        Objects.equals(this.streamDefinition, connectionConfig.streamDefinition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoCreate, streamDefinition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionConfig {\n");
    
    sb.append("    autoCreate: ").append(toIndentedString(autoCreate)).append("\n");
    sb.append("    streamDefinition: ").append(toIndentedString(streamDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

