/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * CreateSourceRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-06T23:45:14.171Z")
public class CreateSourceRequest {
  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("properties")
  private Map<String, Object> properties = null;

  @SerializedName("stream")
  private String stream = null;

  @SerializedName("type")
  private String type = null;

  public CreateSourceRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "read from my kafka topic", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateSourceRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Source name should only contain a maximum of 64 letters, numbers, or _, and start with a letter
   * @return name
  **/
  @ApiModelProperty(example = "my_kafka_source", required = true, value = "Source name should only contain a maximum of 64 letters, numbers, or _, and start with a letter")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateSourceRequest properties(Map<String, Object> properties) {
    this.properties = properties;
    return this;
  }

  public CreateSourceRequest putPropertiesItem(String key, Object propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<String, Object>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Additional properties that required to read the data from source. Please refer to the documentation for this source type
   * @return properties
  **/
  @ApiModelProperty(value = "Additional properties that required to read the data from source. Please refer to the documentation for this source type")
  public Map<String, Object> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Object> properties) {
    this.properties = properties;
  }

  public CreateSourceRequest stream(String stream) {
    this.stream = stream;
    return this;
  }

   /**
   * The name of the target stream that this source writes to. The stream needs to be created first.
   * @return stream
  **/
  @ApiModelProperty(example = "kafak_stream", required = true, value = "The name of the target stream that this source writes to. The stream needs to be created first.")
  public String getStream() {
    return stream;
  }

  public void setStream(String stream) {
    this.stream = stream;
  }

  public CreateSourceRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the source
   * @return type
  **/
  @ApiModelProperty(example = "kafka", required = true, value = "Type of the source")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSourceRequest createSourceRequest = (CreateSourceRequest) o;
    return Objects.equals(this.description, createSourceRequest.description) &&
        Objects.equals(this.name, createSourceRequest.name) &&
        Objects.equals(this.properties, createSourceRequest.properties) &&
        Objects.equals(this.stream, createSourceRequest.stream) &&
        Objects.equals(this.type, createSourceRequest.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, properties, stream, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSourceRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

