/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1beta1
 * Contact: eng@timeplus.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ColumnDef;
import io.swagger.client.model.StreamSetting;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ExternalStreamDef
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-27T00:55:54.866Z")
public class ExternalStreamDef {
  @SerializedName("column")
  private ColumnDef column = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("settings")
  private List<StreamSetting> settings = null;

  public ExternalStreamDef column(ColumnDef column) {
    this.column = column;
    return this;
  }

   /**
   * Get column
   * @return column
  **/
  @ApiModelProperty(value = "")
  public ColumnDef getColumn() {
    return column;
  }

  public void setColumn(ColumnDef column) {
    this.column = column;
  }

  public ExternalStreamDef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExternalStreamDef settings(List<StreamSetting> settings) {
    this.settings = settings;
    return this;
  }

  public ExternalStreamDef addSettingsItem(StreamSetting settingsItem) {
    if (this.settings == null) {
      this.settings = new ArrayList<StreamSetting>();
    }
    this.settings.add(settingsItem);
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @ApiModelProperty(value = "")
  public List<StreamSetting> getSettings() {
    return settings;
  }

  public void setSettings(List<StreamSetting> settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalStreamDef externalStreamDef = (ExternalStreamDef) o;
    return Objects.equals(this.column, externalStreamDef.column) &&
        Objects.equals(this.name, externalStreamDef.name) &&
        Objects.equals(this.settings, externalStreamDef.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(column, name, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalStreamDef {\n");
    
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

