/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GlobalMetricsResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-06T23:45:14.171Z")
public class GlobalMetricsResult {
  @SerializedName("sink_throughput")
  private BigDecimal sinkThroughput = null;

  @SerializedName("source_throughput")
  private BigDecimal sourceThroughput = null;

  @SerializedName("storage")
  private Integer storage = null;

  public GlobalMetricsResult sinkThroughput(BigDecimal sinkThroughput) {
    this.sinkThroughput = sinkThroughput;
    return this;
  }

   /**
   * Get sinkThroughput
   * @return sinkThroughput
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getSinkThroughput() {
    return sinkThroughput;
  }

  public void setSinkThroughput(BigDecimal sinkThroughput) {
    this.sinkThroughput = sinkThroughput;
  }

  public GlobalMetricsResult sourceThroughput(BigDecimal sourceThroughput) {
    this.sourceThroughput = sourceThroughput;
    return this;
  }

   /**
   * Get sourceThroughput
   * @return sourceThroughput
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getSourceThroughput() {
    return sourceThroughput;
  }

  public void setSourceThroughput(BigDecimal sourceThroughput) {
    this.sourceThroughput = sourceThroughput;
  }

  public GlobalMetricsResult storage(Integer storage) {
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getStorage() {
    return storage;
  }

  public void setStorage(Integer storage) {
    this.storage = storage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalMetricsResult globalMetricsResult = (GlobalMetricsResult) o;
    return Objects.equals(this.sinkThroughput, globalMetricsResult.sinkThroughput) &&
        Objects.equals(this.sourceThroughput, globalMetricsResult.sourceThroughput) &&
        Objects.equals(this.storage, globalMetricsResult.storage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sinkThroughput, sourceThroughput, storage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalMetricsResult {\n");
    
    sb.append("    sinkThroughput: ").append(toIndentedString(sinkThroughput)).append("\n");
    sb.append("    sourceThroughput: ").append(toIndentedString(sourceThroughput)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

