/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ResourceMetricsResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-05T18:48:55.783Z")
public class ResourceMetricsResult {
  @SerializedName("id")
  private String id = null;

  @SerializedName("metrics_name")
  private String metricsName = null;

  @SerializedName("metrics_type")
  private String metricsType = null;

  @SerializedName("time")
  private String time = null;

  @SerializedName("value")
  private BigDecimal value = null;

  public ResourceMetricsResult id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResourceMetricsResult metricsName(String metricsName) {
    this.metricsName = metricsName;
    return this;
  }

   /**
   * Get metricsName
   * @return metricsName
  **/
  @ApiModelProperty(value = "")
  public String getMetricsName() {
    return metricsName;
  }

  public void setMetricsName(String metricsName) {
    this.metricsName = metricsName;
  }

  public ResourceMetricsResult metricsType(String metricsType) {
    this.metricsType = metricsType;
    return this;
  }

   /**
   * Get metricsType
   * @return metricsType
  **/
  @ApiModelProperty(value = "")
  public String getMetricsType() {
    return metricsType;
  }

  public void setMetricsType(String metricsType) {
    this.metricsType = metricsType;
  }

  public ResourceMetricsResult time(String time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public String getTime() {
    return time;
  }

  public void setTime(String time) {
    this.time = time;
  }

  public ResourceMetricsResult value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceMetricsResult resourceMetricsResult = (ResourceMetricsResult) o;
    return Objects.equals(this.id, resourceMetricsResult.id) &&
        Objects.equals(this.metricsName, resourceMetricsResult.metricsName) &&
        Objects.equals(this.metricsType, resourceMetricsResult.metricsType) &&
        Objects.equals(this.time, resourceMetricsResult.time) &&
        Objects.equals(this.value, resourceMetricsResult.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, metricsName, metricsType, time, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceMetricsResult {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metricsName: ").append(toIndentedString(metricsName)).append("\n");
    sb.append("    metricsType: ").append(toIndentedString(metricsType)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

