/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1beta1
 * Contact: eng@timeplus.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ProtonSQLAnalyzeColumn;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SQLAnalyzeResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-27T00:55:54.866Z")
public class SQLAnalyzeResult {
  @SerializedName("has_aggr")
  private Boolean hasAggr = null;

  @SerializedName("has_subquery")
  private Boolean hasSubquery = null;

  @SerializedName("has_table_join")
  private Boolean hasTableJoin = null;

  @SerializedName("has_union")
  private Boolean hasUnion = null;

  @SerializedName("original_query")
  private String originalQuery = null;

  @SerializedName("query_type")
  private String queryType = null;

  @SerializedName("required_columns")
  private List<ProtonSQLAnalyzeColumn> requiredColumns = null;

  @SerializedName("result_columns")
  private List<ProtonSQLAnalyzeColumn> resultColumns = null;

  @SerializedName("rewritten_query")
  private String rewrittenQuery = null;

  public SQLAnalyzeResult hasAggr(Boolean hasAggr) {
    this.hasAggr = hasAggr;
    return this;
  }

   /**
   * Get hasAggr
   * @return hasAggr
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasAggr() {
    return hasAggr;
  }

  public void setHasAggr(Boolean hasAggr) {
    this.hasAggr = hasAggr;
  }

  public SQLAnalyzeResult hasSubquery(Boolean hasSubquery) {
    this.hasSubquery = hasSubquery;
    return this;
  }

   /**
   * Get hasSubquery
   * @return hasSubquery
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasSubquery() {
    return hasSubquery;
  }

  public void setHasSubquery(Boolean hasSubquery) {
    this.hasSubquery = hasSubquery;
  }

  public SQLAnalyzeResult hasTableJoin(Boolean hasTableJoin) {
    this.hasTableJoin = hasTableJoin;
    return this;
  }

   /**
   * Get hasTableJoin
   * @return hasTableJoin
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasTableJoin() {
    return hasTableJoin;
  }

  public void setHasTableJoin(Boolean hasTableJoin) {
    this.hasTableJoin = hasTableJoin;
  }

  public SQLAnalyzeResult hasUnion(Boolean hasUnion) {
    this.hasUnion = hasUnion;
    return this;
  }

   /**
   * Get hasUnion
   * @return hasUnion
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasUnion() {
    return hasUnion;
  }

  public void setHasUnion(Boolean hasUnion) {
    this.hasUnion = hasUnion;
  }

  public SQLAnalyzeResult originalQuery(String originalQuery) {
    this.originalQuery = originalQuery;
    return this;
  }

   /**
   * Get originalQuery
   * @return originalQuery
  **/
  @ApiModelProperty(value = "")
  public String getOriginalQuery() {
    return originalQuery;
  }

  public void setOriginalQuery(String originalQuery) {
    this.originalQuery = originalQuery;
  }

  public SQLAnalyzeResult queryType(String queryType) {
    this.queryType = queryType;
    return this;
  }

   /**
   * Get queryType
   * @return queryType
  **/
  @ApiModelProperty(value = "")
  public String getQueryType() {
    return queryType;
  }

  public void setQueryType(String queryType) {
    this.queryType = queryType;
  }

  public SQLAnalyzeResult requiredColumns(List<ProtonSQLAnalyzeColumn> requiredColumns) {
    this.requiredColumns = requiredColumns;
    return this;
  }

  public SQLAnalyzeResult addRequiredColumnsItem(ProtonSQLAnalyzeColumn requiredColumnsItem) {
    if (this.requiredColumns == null) {
      this.requiredColumns = new ArrayList<ProtonSQLAnalyzeColumn>();
    }
    this.requiredColumns.add(requiredColumnsItem);
    return this;
  }

   /**
   * Get requiredColumns
   * @return requiredColumns
  **/
  @ApiModelProperty(value = "")
  public List<ProtonSQLAnalyzeColumn> getRequiredColumns() {
    return requiredColumns;
  }

  public void setRequiredColumns(List<ProtonSQLAnalyzeColumn> requiredColumns) {
    this.requiredColumns = requiredColumns;
  }

  public SQLAnalyzeResult resultColumns(List<ProtonSQLAnalyzeColumn> resultColumns) {
    this.resultColumns = resultColumns;
    return this;
  }

  public SQLAnalyzeResult addResultColumnsItem(ProtonSQLAnalyzeColumn resultColumnsItem) {
    if (this.resultColumns == null) {
      this.resultColumns = new ArrayList<ProtonSQLAnalyzeColumn>();
    }
    this.resultColumns.add(resultColumnsItem);
    return this;
  }

   /**
   * Get resultColumns
   * @return resultColumns
  **/
  @ApiModelProperty(value = "")
  public List<ProtonSQLAnalyzeColumn> getResultColumns() {
    return resultColumns;
  }

  public void setResultColumns(List<ProtonSQLAnalyzeColumn> resultColumns) {
    this.resultColumns = resultColumns;
  }

  public SQLAnalyzeResult rewrittenQuery(String rewrittenQuery) {
    this.rewrittenQuery = rewrittenQuery;
    return this;
  }

   /**
   * Get rewrittenQuery
   * @return rewrittenQuery
  **/
  @ApiModelProperty(value = "")
  public String getRewrittenQuery() {
    return rewrittenQuery;
  }

  public void setRewrittenQuery(String rewrittenQuery) {
    this.rewrittenQuery = rewrittenQuery;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SQLAnalyzeResult sqLAnalyzeResult = (SQLAnalyzeResult) o;
    return Objects.equals(this.hasAggr, sqLAnalyzeResult.hasAggr) &&
        Objects.equals(this.hasSubquery, sqLAnalyzeResult.hasSubquery) &&
        Objects.equals(this.hasTableJoin, sqLAnalyzeResult.hasTableJoin) &&
        Objects.equals(this.hasUnion, sqLAnalyzeResult.hasUnion) &&
        Objects.equals(this.originalQuery, sqLAnalyzeResult.originalQuery) &&
        Objects.equals(this.queryType, sqLAnalyzeResult.queryType) &&
        Objects.equals(this.requiredColumns, sqLAnalyzeResult.requiredColumns) &&
        Objects.equals(this.resultColumns, sqLAnalyzeResult.resultColumns) &&
        Objects.equals(this.rewrittenQuery, sqLAnalyzeResult.rewrittenQuery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasAggr, hasSubquery, hasTableJoin, hasUnion, originalQuery, queryType, requiredColumns, resultColumns, rewrittenQuery);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SQLAnalyzeResult {\n");
    
    sb.append("    hasAggr: ").append(toIndentedString(hasAggr)).append("\n");
    sb.append("    hasSubquery: ").append(toIndentedString(hasSubquery)).append("\n");
    sb.append("    hasTableJoin: ").append(toIndentedString(hasTableJoin)).append("\n");
    sb.append("    hasUnion: ").append(toIndentedString(hasUnion)).append("\n");
    sb.append("    originalQuery: ").append(toIndentedString(originalQuery)).append("\n");
    sb.append("    queryType: ").append(toIndentedString(queryType)).append("\n");
    sb.append("    requiredColumns: ").append(toIndentedString(requiredColumns)).append("\n");
    sb.append("    resultColumns: ").append(toIndentedString(resultColumns)).append("\n");
    sb.append("    rewrittenQuery: ").append(toIndentedString(rewrittenQuery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

