/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ColumnsResp;
import io.swagger.client.model.Owner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Stream
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-06T23:45:14.171Z")
public class Stream {
  @SerializedName("columns")
  private List<ColumnsResp> columns = new ArrayList<ColumnsResp>();

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("created_by")
  private Owner createdBy = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("engine")
  private String engine = null;

  @SerializedName("is_external")
  private Boolean isExternal = null;

  @SerializedName("last_updated_at")
  private String lastUpdatedAt = null;

  @SerializedName("last_updated_by")
  private Owner lastUpdatedBy = null;

  @SerializedName("logstore_retention_bytes")
  private Integer logstoreRetentionBytes = null;

  @SerializedName("logstore_retention_ms")
  private Integer logstoreRetentionMs = null;

  @SerializedName("mode")
  private String mode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("primary_key")
  private String primaryKey = null;

  @SerializedName("ttl")
  private String ttl = null;

  public Stream columns(List<ColumnsResp> columns) {
    this.columns = columns;
    return this;
  }

  public Stream addColumnsItem(ColumnsResp columnsItem) {
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ColumnsResp> getColumns() {
    return columns;
  }

  public void setColumns(List<ColumnsResp> columns) {
    this.columns = columns;
  }

  public Stream createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2023-02-01 23:22:59", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Stream createdBy(Owner createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public Owner getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Owner createdBy) {
    this.createdBy = createdBy;
  }

  public Stream description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "my test stream", required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Stream engine(String engine) {
    this.engine = engine;
    return this;
  }

   /**
   * Get engine
   * @return engine
  **/
  @ApiModelProperty(example = "Stream", required = true, value = "")
  public String getEngine() {
    return engine;
  }

  public void setEngine(String engine) {
    this.engine = engine;
  }

  public Stream isExternal(Boolean isExternal) {
    this.isExternal = isExternal;
    return this;
  }

   /**
   * Get isExternal
   * @return isExternal
  **/
  @ApiModelProperty(example = "false", required = true, value = "")
  public Boolean isIsExternal() {
    return isExternal;
  }

  public void setIsExternal(Boolean isExternal) {
    this.isExternal = isExternal;
  }

  public Stream lastUpdatedAt(String lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

   /**
   * Get lastUpdatedAt
   * @return lastUpdatedAt
  **/
  @ApiModelProperty(example = "2023-02-05 11:12:13", value = "")
  public String getLastUpdatedAt() {
    return lastUpdatedAt;
  }

  public void setLastUpdatedAt(String lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }

  public Stream lastUpdatedBy(Owner lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(value = "")
  public Owner getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(Owner lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public Stream logstoreRetentionBytes(Integer logstoreRetentionBytes) {
    this.logstoreRetentionBytes = logstoreRetentionBytes;
    return this;
  }

   /**
   * Get logstoreRetentionBytes
   * @return logstoreRetentionBytes
  **/
  @ApiModelProperty(example = "1073741824", required = true, value = "")
  public Integer getLogstoreRetentionBytes() {
    return logstoreRetentionBytes;
  }

  public void setLogstoreRetentionBytes(Integer logstoreRetentionBytes) {
    this.logstoreRetentionBytes = logstoreRetentionBytes;
  }

  public Stream logstoreRetentionMs(Integer logstoreRetentionMs) {
    this.logstoreRetentionMs = logstoreRetentionMs;
    return this;
  }

   /**
   * Get logstoreRetentionMs
   * @return logstoreRetentionMs
  **/
  @ApiModelProperty(example = "86400000", required = true, value = "")
  public Integer getLogstoreRetentionMs() {
    return logstoreRetentionMs;
  }

  public void setLogstoreRetentionMs(Integer logstoreRetentionMs) {
    this.logstoreRetentionMs = logstoreRetentionMs;
  }

  public Stream mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Storage mode of stream. Possible values: &#x60;append&#x60;, &#x60;changelog&#x60;, &#x60;changelog_kv&#x60;, &#x60;versioned_kv&#x60;
   * @return mode
  **/
  @ApiModelProperty(example = "append", required = true, value = "Storage mode of stream. Possible values: `append`, `changelog`, `changelog_kv`, `versioned_kv`")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public Stream name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "test_stream", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Stream primaryKey(String primaryKey) {
    this.primaryKey = primaryKey;
    return this;
  }

   /**
   * Expression of primary key, required in &#x60;changelog_kv&#x60;&#x60; and &#x60;versioned_kv&#x60;&#x60; mode
   * @return primaryKey
  **/
  @ApiModelProperty(value = "Expression of primary key, required in `changelog_kv`` and `versioned_kv`` mode")
  public String getPrimaryKey() {
    return primaryKey;
  }

  public void setPrimaryKey(String primaryKey) {
    this.primaryKey = primaryKey;
  }

  public Stream ttl(String ttl) {
    this.ttl = ttl;
    return this;
  }

   /**
   * ORDER_BY     string        &#x60;json:\&quot;order_by_expression\&quot;&#x60; PATTITION_BY string        &#x60;json:\&quot;partition_by_expression\&quot;&#x60;
   * @return ttl
  **/
  @ApiModelProperty(example = "to_datetime(_tp_time) + INTERVAL 7 DAY", required = true, value = "ORDER_BY     string        `json:\"order_by_expression\"` PATTITION_BY string        `json:\"partition_by_expression\"`")
  public String getTtl() {
    return ttl;
  }

  public void setTtl(String ttl) {
    this.ttl = ttl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stream stream = (Stream) o;
    return Objects.equals(this.columns, stream.columns) &&
        Objects.equals(this.createdAt, stream.createdAt) &&
        Objects.equals(this.createdBy, stream.createdBy) &&
        Objects.equals(this.description, stream.description) &&
        Objects.equals(this.engine, stream.engine) &&
        Objects.equals(this.isExternal, stream.isExternal) &&
        Objects.equals(this.lastUpdatedAt, stream.lastUpdatedAt) &&
        Objects.equals(this.lastUpdatedBy, stream.lastUpdatedBy) &&
        Objects.equals(this.logstoreRetentionBytes, stream.logstoreRetentionBytes) &&
        Objects.equals(this.logstoreRetentionMs, stream.logstoreRetentionMs) &&
        Objects.equals(this.mode, stream.mode) &&
        Objects.equals(this.name, stream.name) &&
        Objects.equals(this.primaryKey, stream.primaryKey) &&
        Objects.equals(this.ttl, stream.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, createdAt, createdBy, description, engine, isExternal, lastUpdatedAt, lastUpdatedBy, logstoreRetentionBytes, logstoreRetentionMs, mode, name, primaryKey, ttl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stream {\n");
    
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    engine: ").append(toIndentedString(engine)).append("\n");
    sb.append("    isExternal: ").append(toIndentedString(isExternal)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    logstoreRetentionBytes: ").append(toIndentedString(logstoreRetentionBytes)).append("\n");
    sb.append("    logstoreRetentionMs: ").append(toIndentedString(logstoreRetentionMs)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    primaryKey: ").append(toIndentedString(primaryKey)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

