/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TimeColumns
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-05T18:48:55.783Z")
public class TimeColumns {
  @SerializedName("eventTime")
  private Integer eventTime = null;

  @SerializedName("indexTime")
  private Integer indexTime = null;

  @SerializedName("windowEnd")
  private Integer windowEnd = null;

  @SerializedName("windowStart")
  private Integer windowStart = null;

  public TimeColumns eventTime(Integer eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getEventTime() {
    return eventTime;
  }

  public void setEventTime(Integer eventTime) {
    this.eventTime = eventTime;
  }

  public TimeColumns indexTime(Integer indexTime) {
    this.indexTime = indexTime;
    return this;
  }

   /**
   * Get indexTime
   * @return indexTime
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getIndexTime() {
    return indexTime;
  }

  public void setIndexTime(Integer indexTime) {
    this.indexTime = indexTime;
  }

  public TimeColumns windowEnd(Integer windowEnd) {
    this.windowEnd = windowEnd;
    return this;
  }

   /**
   * Get windowEnd
   * @return windowEnd
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getWindowEnd() {
    return windowEnd;
  }

  public void setWindowEnd(Integer windowEnd) {
    this.windowEnd = windowEnd;
  }

  public TimeColumns windowStart(Integer windowStart) {
    this.windowStart = windowStart;
    return this;
  }

   /**
   * Get windowStart
   * @return windowStart
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getWindowStart() {
    return windowStart;
  }

  public void setWindowStart(Integer windowStart) {
    this.windowStart = windowStart;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeColumns timeColumns = (TimeColumns) o;
    return Objects.equals(this.eventTime, timeColumns.eventTime) &&
        Objects.equals(this.indexTime, timeColumns.indexTime) &&
        Objects.equals(this.windowEnd, timeColumns.windowEnd) &&
        Objects.equals(this.windowStart, timeColumns.windowStart);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventTime, indexTime, windowEnd, windowStart);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeColumns {\n");
    
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    indexTime: ").append(toIndentedString(indexTime)).append("\n");
    sb.append("    windowEnd: ").append(toIndentedString(windowEnd)).append("\n");
    sb.append("    windowStart: ").append(toIndentedString(windowStart)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

