/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Owner;
import io.swagger.client.model.UDFArgument;
import io.swagger.client.model.UDFAuthContext;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UDF
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-06T23:45:14.171Z")
public class UDF {
  @SerializedName("arguments")
  private List<UDFArgument> arguments = null;

  @SerializedName("auth_context")
  private UDFAuthContext authContext = null;

  @SerializedName("auth_method")
  private String authMethod = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("created_by")
  private Owner createdBy = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("is_aggregation")
  private Boolean isAggregation = null;

  @SerializedName("last_updated_at")
  private String lastUpdatedAt = null;

  @SerializedName("last_updated_by")
  private Owner lastUpdatedBy = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("return_type")
  private String returnType = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("url")
  private String url = null;

  public UDF arguments(List<UDFArgument> arguments) {
    this.arguments = arguments;
    return this;
  }

  public UDF addArgumentsItem(UDFArgument argumentsItem) {
    if (this.arguments == null) {
      this.arguments = new ArrayList<UDFArgument>();
    }
    this.arguments.add(argumentsItem);
    return this;
  }

   /**
   * The input argument of the UDF   * For UDA: the number and type of arguments should be consistent with the main function of UDA.     the type should be the data types of proton not javascript types. It only supports int8/16/32/64, uint8/16/32/64,
   * @return arguments
  **/
  @ApiModelProperty(value = "The input argument of the UDF   * For UDA: the number and type of arguments should be consistent with the main function of UDA.     the type should be the data types of proton not javascript types. It only supports int8/16/32/64, uint8/16/32/64,")
  public List<UDFArgument> getArguments() {
    return arguments;
  }

  public void setArguments(List<UDFArgument> arguments) {
    this.arguments = arguments;
  }

  public UDF authContext(UDFAuthContext authContext) {
    this.authContext = authContext;
    return this;
  }

   /**
   * Get authContext
   * @return authContext
  **/
  @ApiModelProperty(value = "")
  public UDFAuthContext getAuthContext() {
    return authContext;
  }

  public void setAuthContext(UDFAuthContext authContext) {
    this.authContext = authContext;
  }

  public UDF authMethod(String authMethod) {
    this.authMethod = authMethod;
    return this;
  }

   /**
   * Get authMethod
   * @return authMethod
  **/
  @ApiModelProperty(value = "")
  public String getAuthMethod() {
    return authMethod;
  }

  public void setAuthMethod(String authMethod) {
    this.authMethod = authMethod;
  }

  public UDF createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2023-02-01 23:22:59", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public UDF createdBy(Owner createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public Owner getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Owner createdBy) {
    this.createdBy = createdBy;
  }

  public UDF description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UDF isAggregation(Boolean isAggregation) {
    this.isAggregation = isAggregation;
    return this;
  }

   /**
   * Whether it is an aggregation function. Only valid when type is &#39;javascript&#39;
   * @return isAggregation
  **/
  @ApiModelProperty(value = "Whether it is an aggregation function. Only valid when type is 'javascript'")
  public Boolean isIsAggregation() {
    return isAggregation;
  }

  public void setIsAggregation(Boolean isAggregation) {
    this.isAggregation = isAggregation;
  }

  public UDF lastUpdatedAt(String lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

   /**
   * Get lastUpdatedAt
   * @return lastUpdatedAt
  **/
  @ApiModelProperty(example = "2023-02-05 11:12:13", value = "")
  public String getLastUpdatedAt() {
    return lastUpdatedAt;
  }

  public void setLastUpdatedAt(String lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }

  public UDF lastUpdatedBy(Owner lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(value = "")
  public Owner getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(Owner lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public UDF name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UDF returnType(String returnType) {
    this.returnType = returnType;
    return this;
  }

   /**
   * The erturn type of the UDF   * For UDA: if it returns a single value, the return type is the corresponding data type of Timeplus.     It supports the same types of input arguments, except for datetime, it only supports DateTime64(3).
   * @return returnType
  **/
  @ApiModelProperty(value = "The erturn type of the UDF   * For UDA: if it returns a single value, the return type is the corresponding data type of Timeplus.     It supports the same types of input arguments, except for datetime, it only supports DateTime64(3).")
  public String getReturnType() {
    return returnType;
  }

  public void setReturnType(String returnType) {
    this.returnType = returnType;
  }

  public UDF source(String source) {
    this.source = source;
    return this;
  }

   /**
   * The source code of the UDA. There are functions to be defined:  * main function: with the same name as UDA. Timeplus calls this function for each input row. The main function can return two types of result: object or simple data type    - If it returns an object, the object is like {“emit”: true, “result”: …}. ‘Emit’ (boolean) property tells Timeplus whether or not the result should emit. ‘result’ is the current aggregate result, if ‘emit’ is false, the result will be ignored by Timeplus. Timeplus will convert the ‘result’ property of v8 to the data types defined when creating UDA.    - If it returns a simple data type, Timeplus considers the return data as the result to be emitted immediately. It converts the return data to the corresponding data type and Timeplus emits the aggregating result.    - Once UDA tells Timeplus to emit the data, UDA takes the full responsibility to clear the internal state, prepare and restart a new aggregating window, et al.  * state function: which returns the serialized state of all internal states of UDA in string. The UDA takes the responsibility therefore Timeplus can choose to persist the internal state of UDA for query recovery.  * init function: the input of this function is the string of serialized state of the internal states UDA. Timeplus calls this function when it wants to recover the aggregation function with the persisted internal state.
   * @return source
  **/
  @ApiModelProperty(value = "The source code of the UDA. There are functions to be defined:  * main function: with the same name as UDA. Timeplus calls this function for each input row. The main function can return two types of result: object or simple data type    - If it returns an object, the object is like {“emit”: true, “result”: …}. ‘Emit’ (boolean) property tells Timeplus whether or not the result should emit. ‘result’ is the current aggregate result, if ‘emit’ is false, the result will be ignored by Timeplus. Timeplus will convert the ‘result’ property of v8 to the data types defined when creating UDA.    - If it returns a simple data type, Timeplus considers the return data as the result to be emitted immediately. It converts the return data to the corresponding data type and Timeplus emits the aggregating result.    - Once UDA tells Timeplus to emit the data, UDA takes the full responsibility to clear the internal state, prepare and restart a new aggregating window, et al.  * state function: which returns the serialized state of all internal states of UDA in string. The UDA takes the responsibility therefore Timeplus can choose to persist the internal state of UDA for query recovery.  * init function: the input of this function is the string of serialized state of the internal states UDA. Timeplus calls this function when it wants to recover the aggregation function with the persisted internal state.")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public UDF type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Either &#x60;javascript&#x60; or &#x60;remote&#x60;
   * @return type
  **/
  @ApiModelProperty(value = "Either `javascript` or `remote`")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public UDF url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UDF UDF = (UDF) o;
    return Objects.equals(this.arguments, UDF.arguments) &&
        Objects.equals(this.authContext, UDF.authContext) &&
        Objects.equals(this.authMethod, UDF.authMethod) &&
        Objects.equals(this.createdAt, UDF.createdAt) &&
        Objects.equals(this.createdBy, UDF.createdBy) &&
        Objects.equals(this.description, UDF.description) &&
        Objects.equals(this.isAggregation, UDF.isAggregation) &&
        Objects.equals(this.lastUpdatedAt, UDF.lastUpdatedAt) &&
        Objects.equals(this.lastUpdatedBy, UDF.lastUpdatedBy) &&
        Objects.equals(this.name, UDF.name) &&
        Objects.equals(this.returnType, UDF.returnType) &&
        Objects.equals(this.source, UDF.source) &&
        Objects.equals(this.type, UDF.type) &&
        Objects.equals(this.url, UDF.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arguments, authContext, authMethod, createdAt, createdBy, description, isAggregation, lastUpdatedAt, lastUpdatedBy, name, returnType, source, type, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UDF {\n");
    
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    authContext: ").append(toIndentedString(authContext)).append("\n");
    sb.append("    authMethod: ").append(toIndentedString(authMethod)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isAggregation: ").append(toIndentedString(isAggregation)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    returnType: ").append(toIndentedString(returnType)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

