/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UpdateStreamRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-06T23:45:14.171Z")
public class UpdateStreamRequest {
  @SerializedName("description")
  private String description = null;

  @SerializedName("logstore_retention_bytes")
  private Integer logstoreRetentionBytes = null;

  @SerializedName("logstore_retention_ms")
  private Integer logstoreRetentionMs = null;

  @SerializedName("ttl_expression")
  private String ttlExpression = null;

  public UpdateStreamRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UpdateStreamRequest logstoreRetentionBytes(Integer logstoreRetentionBytes) {
    this.logstoreRetentionBytes = logstoreRetentionBytes;
    return this;
  }

   /**
   * The max size a stream can grow. Defaulted to 10 GiB
   * @return logstoreRetentionBytes
  **/
  @ApiModelProperty(example = "10737418240", value = "The max size a stream can grow. Defaulted to 10 GiB")
  public Integer getLogstoreRetentionBytes() {
    return logstoreRetentionBytes;
  }

  public void setLogstoreRetentionBytes(Integer logstoreRetentionBytes) {
    this.logstoreRetentionBytes = logstoreRetentionBytes;
  }

  public UpdateStreamRequest logstoreRetentionMs(Integer logstoreRetentionMs) {
    this.logstoreRetentionMs = logstoreRetentionMs;
    return this;
  }

   /**
   * The max time the data can be retained in the stream. Defaulted to 7 days
   * @return logstoreRetentionMs
  **/
  @ApiModelProperty(example = "604800000", value = "The max time the data can be retained in the stream. Defaulted to 7 days")
  public Integer getLogstoreRetentionMs() {
    return logstoreRetentionMs;
  }

  public void setLogstoreRetentionMs(Integer logstoreRetentionMs) {
    this.logstoreRetentionMs = logstoreRetentionMs;
  }

  public UpdateStreamRequest ttlExpression(String ttlExpression) {
    this.ttlExpression = ttlExpression;
    return this;
  }

   /**
   * Get ttlExpression
   * @return ttlExpression
  **/
  @ApiModelProperty(value = "")
  public String getTtlExpression() {
    return ttlExpression;
  }

  public void setTtlExpression(String ttlExpression) {
    this.ttlExpression = ttlExpression;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateStreamRequest updateStreamRequest = (UpdateStreamRequest) o;
    return Objects.equals(this.description, updateStreamRequest.description) &&
        Objects.equals(this.logstoreRetentionBytes, updateStreamRequest.logstoreRetentionBytes) &&
        Objects.equals(this.logstoreRetentionMs, updateStreamRequest.logstoreRetentionMs) &&
        Objects.equals(this.ttlExpression, updateStreamRequest.ttlExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, logstoreRetentionBytes, logstoreRetentionMs, ttlExpression);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateStreamRequest {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    logstoreRetentionBytes: ").append(toIndentedString(logstoreRetentionBytes)).append("\n");
    sb.append("    logstoreRetentionMs: ").append(toIndentedString(logstoreRetentionMs)).append("\n");
    sb.append("    ttlExpression: ").append(toIndentedString(ttlExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

