/*
 * Timeplus
 * Welcome to the Timeplus HTTP REST API specification.
 *
 * OpenAPI spec version: v1
 * Contact: support@timeplus.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.ErrorResponse;
import io.swagger.client.model.ExternalStreamDef;
import io.swagger.client.model.IngestData;
import io.swagger.client.model.Stream;
import io.swagger.client.model.StreamDef;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StreamsV1beta1Api {
    private ApiClient apiClient;

    public StreamsV1beta1Api() {
        this(Configuration.getDefaultApiClient());
    }

    public StreamsV1beta1Api(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for v1beta1StreamsExternalPost
     * @param stream create external stream request parameters (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsExternalPostCall(ExternalStreamDef stream, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = stream;

        // create path and map variables
        String localVarPath = "/v1beta1/streams/external";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v1beta1StreamsExternalPostValidateBeforeCall(ExternalStreamDef stream, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'stream' is set
        if (stream == null) {
            throw new ApiException("Missing the required parameter 'stream' when calling v1beta1StreamsExternalPost(Async)");
        }
        

        com.squareup.okhttp.Call call = v1beta1StreamsExternalPostCall(stream, progressListener, progressRequestListener);
        return call;

    }

    /**
     * create an external stream.
     * Create an external stream.
     * @param stream create external stream request parameters (required)
     * @return ExternalStreamDef
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ExternalStreamDef v1beta1StreamsExternalPost(ExternalStreamDef stream) throws ApiException {
        ApiResponse<ExternalStreamDef> resp = v1beta1StreamsExternalPostWithHttpInfo(stream);
        return resp.getData();
    }

    /**
     * create an external stream.
     * Create an external stream.
     * @param stream create external stream request parameters (required)
     * @return ApiResponse&lt;ExternalStreamDef&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ExternalStreamDef> v1beta1StreamsExternalPostWithHttpInfo(ExternalStreamDef stream) throws ApiException {
        com.squareup.okhttp.Call call = v1beta1StreamsExternalPostValidateBeforeCall(stream, null, null);
        Type localVarReturnType = new TypeToken<ExternalStreamDef>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * create an external stream. (asynchronously)
     * Create an external stream.
     * @param stream create external stream request parameters (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsExternalPostAsync(ExternalStreamDef stream, final ApiCallback<ExternalStreamDef> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v1beta1StreamsExternalPostValidateBeforeCall(stream, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ExternalStreamDef>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for v1beta1StreamsGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1beta1/streams";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v1beta1StreamsGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = v1beta1StreamsGetCall(progressListener, progressRequestListener);
        return call;

    }

    /**
     * list streams.
     * Get all streams.
     * @return List&lt;Stream&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<Stream> v1beta1StreamsGet() throws ApiException {
        ApiResponse<List<Stream>> resp = v1beta1StreamsGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * list streams.
     * Get all streams.
     * @return ApiResponse&lt;List&lt;Stream&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<Stream>> v1beta1StreamsGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = v1beta1StreamsGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<List<Stream>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * list streams. (asynchronously)
     * Get all streams.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsGetAsync(final ApiCallback<List<Stream>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v1beta1StreamsGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<Stream>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for v1beta1StreamsNameDelete
     * @param name stream name (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsNameDeleteCall(String name, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1beta1/streams/{name}"
            .replaceAll("\\{" + "name" + "\\}", apiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v1beta1StreamsNameDeleteValidateBeforeCall(String name, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling v1beta1StreamsNameDelete(Async)");
        }
        

        com.squareup.okhttp.Call call = v1beta1StreamsNameDeleteCall(name, progressListener, progressRequestListener);
        return call;

    }

    /**
     * delete a stream.
     * Delete the stream with the given name.
     * @param name stream name (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void v1beta1StreamsNameDelete(String name) throws ApiException {
        v1beta1StreamsNameDeleteWithHttpInfo(name);
    }

    /**
     * delete a stream.
     * Delete the stream with the given name.
     * @param name stream name (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> v1beta1StreamsNameDeleteWithHttpInfo(String name) throws ApiException {
        com.squareup.okhttp.Call call = v1beta1StreamsNameDeleteValidateBeforeCall(name, null, null);
        return apiClient.execute(call);
    }

    /**
     * delete a stream. (asynchronously)
     * Delete the stream with the given name.
     * @param name stream name (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsNameDeleteAsync(String name, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v1beta1StreamsNameDeleteValidateBeforeCall(name, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for v1beta1StreamsNameIngestPost
     * @param name stream name (required)
     * @param query ingest data (required)
     * @param format enfoce payload format, if it is set, it overwrite the Content-Type header (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsNameIngestPostCall(String name, IngestData query, String format, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = query;

        // create path and map variables
        String localVarPath = "/v1beta1/streams/{name}/ingest"
            .replaceAll("\\{" + "name" + "\\}", apiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (format != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("format", format));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/vnd.timeplus+json", "application/json;format=compat", "application/vnd.timeplus+json;format=compat", "application/json;format=stream", "application/vnd.timeplus+json;format=stream", "application/x-ndjson", "text/plain", "text/plain;format=raw", "text/plain;format=lines"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v1beta1StreamsNameIngestPostValidateBeforeCall(String name, IngestData query, String format, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling v1beta1StreamsNameIngestPost(Async)");
        }
        
        // verify the required parameter 'query' is set
        if (query == null) {
            throw new ApiException("Missing the required parameter 'query' when calling v1beta1StreamsNameIngestPost(Async)");
        }
        

        com.squareup.okhttp.Call call = v1beta1StreamsNameIngestPostCall(name, query, format, progressListener, progressRequestListener);
        return call;

    }

    /**
     * ingest data.
     * Ingest data to a stream with the given name. For formats are supported: * compact JSON: when &#x60;Content-Type&#x60; is set to one of &#x60;application/json&#x60;, &#x60;application/json;format&#x3D;compact&#x60;, &#x60;application/vnd.timeplus+json&#x60;, &#x60;application/vnd.timeplus+json;format&#x3D;compat&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;compact&#x60;. And this is the API&#39;s default format. * JSON stream: when &#x60;Content-Type&#x60; is set to one of &#x60;application/json;format&#x3D;streaming&#x60;, &#x60;application/vnd.timeplus+json;format&#x3D;streaming&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;streaming&#x60;. * raw string: when &#x60;Content-Type&#x60; is set to one of &#x60;text/plain&#x60;, &#x60;text/plain;format&#x3D;raw&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;raw&#x60;. * string lines: when &#x60;Content-Type&#x60; is set to &#x60;text/plain;format&#x3D;lines&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;lines&#x60;. 
     * @param name stream name (required)
     * @param query ingest data (required)
     * @param format enfoce payload format, if it is set, it overwrite the Content-Type header (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void v1beta1StreamsNameIngestPost(String name, IngestData query, String format) throws ApiException {
        v1beta1StreamsNameIngestPostWithHttpInfo(name, query, format);
    }

    /**
     * ingest data.
     * Ingest data to a stream with the given name. For formats are supported: * compact JSON: when &#x60;Content-Type&#x60; is set to one of &#x60;application/json&#x60;, &#x60;application/json;format&#x3D;compact&#x60;, &#x60;application/vnd.timeplus+json&#x60;, &#x60;application/vnd.timeplus+json;format&#x3D;compat&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;compact&#x60;. And this is the API&#39;s default format. * JSON stream: when &#x60;Content-Type&#x60; is set to one of &#x60;application/json;format&#x3D;streaming&#x60;, &#x60;application/vnd.timeplus+json;format&#x3D;streaming&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;streaming&#x60;. * raw string: when &#x60;Content-Type&#x60; is set to one of &#x60;text/plain&#x60;, &#x60;text/plain;format&#x3D;raw&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;raw&#x60;. * string lines: when &#x60;Content-Type&#x60; is set to &#x60;text/plain;format&#x3D;lines&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;lines&#x60;. 
     * @param name stream name (required)
     * @param query ingest data (required)
     * @param format enfoce payload format, if it is set, it overwrite the Content-Type header (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> v1beta1StreamsNameIngestPostWithHttpInfo(String name, IngestData query, String format) throws ApiException {
        com.squareup.okhttp.Call call = v1beta1StreamsNameIngestPostValidateBeforeCall(name, query, format, null, null);
        return apiClient.execute(call);
    }

    /**
     * ingest data. (asynchronously)
     * Ingest data to a stream with the given name. For formats are supported: * compact JSON: when &#x60;Content-Type&#x60; is set to one of &#x60;application/json&#x60;, &#x60;application/json;format&#x3D;compact&#x60;, &#x60;application/vnd.timeplus+json&#x60;, &#x60;application/vnd.timeplus+json;format&#x3D;compat&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;compact&#x60;. And this is the API&#39;s default format. * JSON stream: when &#x60;Content-Type&#x60; is set to one of &#x60;application/json;format&#x3D;streaming&#x60;, &#x60;application/vnd.timeplus+json;format&#x3D;streaming&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;streaming&#x60;. * raw string: when &#x60;Content-Type&#x60; is set to one of &#x60;text/plain&#x60;, &#x60;text/plain;format&#x3D;raw&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;raw&#x60;. * string lines: when &#x60;Content-Type&#x60; is set to &#x60;text/plain;format&#x3D;lines&#x60;, or set &#x60;format&#x60; query parameter with value &#x60;lines&#x60;. 
     * @param name stream name (required)
     * @param query ingest data (required)
     * @param format enfoce payload format, if it is set, it overwrite the Content-Type header (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsNameIngestPostAsync(String name, IngestData query, String format, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v1beta1StreamsNameIngestPostValidateBeforeCall(name, query, format, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for v1beta1StreamsNamePut
     * @param name name of the stream (required)
     * @param stream update stream request parameters (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsNamePutCall(String name, StreamDef stream, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = stream;

        // create path and map variables
        String localVarPath = "/v1beta1/streams/{name}"
            .replaceAll("\\{" + "name" + "\\}", apiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v1beta1StreamsNamePutValidateBeforeCall(String name, StreamDef stream, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling v1beta1StreamsNamePut(Async)");
        }
        
        // verify the required parameter 'stream' is set
        if (stream == null) {
            throw new ApiException("Missing the required parameter 'stream' when calling v1beta1StreamsNamePut(Async)");
        }
        

        com.squareup.okhttp.Call call = v1beta1StreamsNamePutCall(name, stream, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Update a stream.
     * Update the specific stream with the given name. Currently only retention policy and TTL are supported.
     * @param name name of the stream (required)
     * @param stream update stream request parameters (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void v1beta1StreamsNamePut(String name, StreamDef stream) throws ApiException {
        v1beta1StreamsNamePutWithHttpInfo(name, stream);
    }

    /**
     * Update a stream.
     * Update the specific stream with the given name. Currently only retention policy and TTL are supported.
     * @param name name of the stream (required)
     * @param stream update stream request parameters (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> v1beta1StreamsNamePutWithHttpInfo(String name, StreamDef stream) throws ApiException {
        com.squareup.okhttp.Call call = v1beta1StreamsNamePutValidateBeforeCall(name, stream, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update a stream. (asynchronously)
     * Update the specific stream with the given name. Currently only retention policy and TTL are supported.
     * @param name name of the stream (required)
     * @param stream update stream request parameters (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsNamePutAsync(String name, StreamDef stream, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v1beta1StreamsNamePutValidateBeforeCall(name, stream, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for v1beta1StreamsPost
     * @param stream create stream request parameters (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsPostCall(StreamDef stream, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = stream;

        // create path and map variables
        String localVarPath = "/v1beta1/streams";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v1beta1StreamsPostValidateBeforeCall(StreamDef stream, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'stream' is set
        if (stream == null) {
            throw new ApiException("Missing the required parameter 'stream' when calling v1beta1StreamsPost(Async)");
        }
        

        com.squareup.okhttp.Call call = v1beta1StreamsPostCall(stream, progressListener, progressRequestListener);
        return call;

    }

    /**
     * create a stream.
     * Create a stream.
     * @param stream create stream request parameters (required)
     * @return StreamDef
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public StreamDef v1beta1StreamsPost(StreamDef stream) throws ApiException {
        ApiResponse<StreamDef> resp = v1beta1StreamsPostWithHttpInfo(stream);
        return resp.getData();
    }

    /**
     * create a stream.
     * Create a stream.
     * @param stream create stream request parameters (required)
     * @return ApiResponse&lt;StreamDef&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<StreamDef> v1beta1StreamsPostWithHttpInfo(StreamDef stream) throws ApiException {
        com.squareup.okhttp.Call call = v1beta1StreamsPostValidateBeforeCall(stream, null, null);
        Type localVarReturnType = new TypeToken<StreamDef>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * create a stream. (asynchronously)
     * Create a stream.
     * @param stream create stream request parameters (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v1beta1StreamsPostAsync(StreamDef stream, final ApiCallback<StreamDef> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v1beta1StreamsPostValidateBeforeCall(stream, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<StreamDef>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
